### ISSUE TITLE
Error running ulysses

### ISSUE THREAD

**Issue by hangphan** [gillet/ulysses#1]
Hi, I tried running the example given in the package but I ran into this error after running ./Ulysses.py 

Results written to ulysses/example/example.bam_Ulysses_[NRT/INS/RT]_by[PS/SV].[stats.]csv
End of inter-chromosomal SV detection
Tue Mar 17 14:46:37 GMT 2015
Traceback (most recent call last):
  File "./Ulysses.py", line 238, in <module>
    U.write_VCF(params["out"]+".vcf",dicovcf, params["vcf"], params)
  File "/gpfs0/users/bsg/hangphan/programs/ulysses/Ulysse_utils.py", line 76, in write_VCF
    _format_vcffile(dictreader, vcffile, Header, sv, fdr_threshlod, lib, params)
  File "ulysses/Ulysse_utils.py", line 229, in _format_vcffile
    QUAL = int(abs(-10*math.log(float(line[_tsv_fields[19]]))))
IndexError: tuple index out of range

**Comment by gillet** [comment]
Hi,

I think this is symptomatic of an issue during the compilation of some R code (probamaxdist.c file).
Try to go to ulysses directory and to compile it by hand :
cd ulysses
rm  probamaxdist.so  probamaxdist.o
R CMD SHLIB probamaxdist.c

If i am right it will not work but the error displayed will help to correct the issue (a library might be missing/out of date...). 

Best,
Alex

**Comment by hangphan** [comment]
I recompiled it according to what you suggested,
but the cvs files still do not contain the pval column which should be at the end of the row. Thus I still have the same error as before. 

Library;(pairof)chromosome(s);ID;nbRP;nbA;nbB;left_borderA;right_borderA;deltaA;cen_posA;left_borderB;right_borderB;deltaB;cen_posB;SV_size_min;SV_size_max;p-balanced;cov;AvrQual

Can you check on your side whether this is happening?

**Comment by gillet** [comment]
The lack of the pval column is due to R crashing. Usually because compilation went wrong but it might also be due to something else. I will need more information to understand what is happening. Can you please paste here or send me by by email the stdout output of ulysses when you run the detection ?

**Comment by hangphan** [comment]
I will send it to you tomorrow morning.

Best
Hang

**Comment by hangphan** [comment]
Hi,

 below is the log of the run on the example given.

Hope you can figure out what was happening

Best

Hang

---

Wed Mar 18 12:08:28 GMT 2015

Wed Mar 18 12:10:40 GMT 2015

Wed Mar 18 12:12:57 GMT 2015

Wed Mar 18 12:14:48 GMT 2015

Wed Mar 18 12:18:18 GMT 2015

Wed Mar 18 12:18:18 GMT 2015

Wed Mar 18 12:18:24 GMT 2015

Wed Mar 18 12:21:35 GMT 2015

oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

 ---  ULYSSES v1.0 20141023  ---

   Ulysses: Accurate detection of rare structural variations from high
coverage genome sequencing

 Alexandre Gillet, Hugues Richard, Gilles Fischer and Ingrid Lafontaine

 http://www.lcqb.upmc.fr/ulysses

 Copyright UPMC - CNRS

oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Parameter file : example_params

All SV type will be detected

Duplications

Inversions

inter chromosomal variants

Deletions

MINPS for a deletion: 2

Processing chr16 - Nb of discordant PS: 5087 - 2015-03-18 12:08:24.555014

Processing chr3 - Nb of discordant PS: 2411 - 2015-03-18 12:08:25.635558

Processing chr5 - Nb of discordant PS: 3108 - 2015-03-18 12:08:28.525889

Detection done

Report file :
/gpfs0/users/bsg/hangphan/programs/ulysses/example/example.bam_Ulysses.DEL.report.out

results written to
/gpfs0/users/bsg/hangphan/programs/ulysses/example/example.bam_Ulysses_deletions_by[PS/SV].csv

results written to
/gpfs0/users/bsg/hangphan/programs/ulysses/example/example.bam_Ulysses_deletions_by[PS/SV].csv

---

Starting coverage calculation

Added local coverage to
/gpfs0/users/bsg/hangphan/programs/ulysses/example/example.bam_Ulysses_deletions_bySV.csv

---

Statistics done

Execution halted

---

Starting coverage calculation

Added local coverage to
/gpfs0/users/bsg/hangphan/programs/ulysses/example/example.bam_Ulysses_small_insertions_bySV.csv

---

Statistics done

Execution halted

End of deletion detection

MINPS for duplications: 1

Processing chr16 - Nb of discordant PS: 69 - 2015-03-18 12:04

Processing chr3 - Nb of discordant PS: 259 - 2015-03-18 12:04

Processing chr5 - Nb of discordant PS: 29 - 2015-03-18 12:04

Detection done

Statistics done

Execution halted

End of duplication detection

MINPS for inversions: 1

Processing chr16 - Nb of discordant PS: 213 - 2015-03-18 12:13

Processing chr3 - Nb of discordant PS: 42 - 2015-03-18 12:13

Processing chr5 - Nb of discordant PS: 103 - 2015-03-18 12:13

Detection done

Statistics done

Execution halted

End of inversions detection

***************\* Detection of Inter chromosomal SV

Centromeres positions not given. Distinction between INS and RT will not be
optimal

PS loaded from BAM file

Execution halted

Execution halted

Execution halted

**\* Processing chr16-chr3 205 ***

```
Starting Etape 1: PS sorting by orientation 2015-03-18 12:18:18.518520

Starting Detection 2015-03-18 12:18:18.519870
```

Orientation "--"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:18.519886

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:18.528243

```
Starting Etape 4: Makes the list of potential SVs from 49 left groups
```

2015-03-18 12:18:18.531445

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:18.532193
```

Orientation "++"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:18.533593

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:18.542706

```
Starting Etape 4: Makes the list of potential SVs from 47 left groups
```

2015-03-18 12:18:18.546367

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:18.547116
```

Orientation "-+"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:18.548530

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:18.555534

```
Starting Etape 4: Makes the list of potential SVs from 45 left groups
```

2015-03-18 12:18:18.558028

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:18.558551
```

Orientation "+-"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:18.559583

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:18.565427

```
Starting Etape 4: Makes the list of potential SVs from 42 left groups
```

2015-03-18 12:18:18.567710

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:18.568150

Starting Etape 6: Remove SV duplicates 2015-03-18 12:18:18.569032

Start affichage 2015-03-18 12:18:18.569184
```

**\* Processing chr16-chr5 846 ***

```
Starting Etape 1: PS sorting by orientation 2015-03-18 12:18:18.883893

Starting Detection 2015-03-18 12:18:18.887935
```

Orientation "--"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:18.887951

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:18.908138

```
Starting Etape 4: Makes the list of potential SVs from 82 left groups
```

2015-03-18 12:18:18.912358

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:18.913203
```

Orientation "++"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:18.914801

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:18.928657

```
Starting Etape 4: Makes the list of potential SVs from 69 left groups
```

2015-03-18 12:18:18.932351

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:18.933058
```

50 / 69 / 0 / 1

Orientation "-+"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:18.934431

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:19.127027

```
Starting Etape 4: Makes the list of potential SVs from 85 left groups
```

2015-03-18 12:18:19.468097

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:21.316059
```

Orientation "+-"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:21.351162

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:21.581484

```
Starting Etape 4: Makes the list of potential SVs from 92 left groups
```

2015-03-18 12:18:21.929184

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:23.463195

Starting Etape 6: Remove SV duplicates 2015-03-18 12:18:23.495387

Start affichage 2015-03-18 12:18:23.498835
```

**\* Processing chr3-chr5 110 ***

```
Starting Etape 1: PS sorting by orientation 2015-03-18 12:18:24.050903

Starting Detection 2015-03-18 12:18:24.053141
```

Orientation "--"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:24.053157

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:24.055327

```
Starting Etape 4: Makes the list of potential SVs from 25 left groups
```

2015-03-18 12:18:24.059097

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:24.059512
```

Orientation "++"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:24.060118

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:24.063244

```
Starting Etape 4: Makes the list of potential SVs from 31 left groups
```

2015-03-18 12:18:24.064617

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:24.064975
```

Orientation "-+"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:24.065669

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:24.067598

```
Starting Etape 4: Makes the list of potential SVs from 24 left groups
```

2015-03-18 12:18:24.068716

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:24.068986
```

Orientation "+-"

```
Starting Etape 2: Making groups of PS in the same orientation
```

2015-03-18 12:18:24.069468

```
Starting Etape 3: Individual opposite PS collection 2015-03-18
```

12:18:24.072194

```
Starting Etape 4: Makes the list of potential SVs from 29 left groups
```

2015-03-18 12:18:24.073347

```
Starting Etape 5: Classification of SVs 2015-03-18 12:18:24.073619

Starting Etape 6: Remove SV duplicates 2015-03-18 12:18:24.074184

Start affichage 2015-03-18 12:18:24.074324
```

Statistics done

Execution halted

Statistics done

Execution halted

Statistics done

Execution halted

Detection done

Report file :
/gpfs0/users/bsg/hangphan/programs/ulysses/example/example.bam_Ulysses.INTER.report.out

Results written to
/gpfs0/users/bsg/hangphan/programs/ulysses/example/example.bam_Ulysses_[NRT/INS/RT]_by[PS/SV].[stats.]csv

End of inter-chromosomal SV detection

Traceback (most recent call last):

  File "./Ulysses.py", line 238, in <module>

```
U.write_VCF(params["out"]+".vcf",dicovcf, params["vcf"], params)
```

  File "/gpfs0/users/bsg/hangphan/programs/ulysses/Ulysse_utils.py", line
76, in write_VCF

```
_format_vcffile(dictreader, vcffile, Header, sv, fdr_threshlod, lib,
```

params)

  File "/gpfs0/users/bsg/hangphan/programs/ulysses/Ulysse_utils.py", line
229, in _format_vcffile

```
QUAL = int(abs(-10*math.log(float(line[_tsv_fields[19]]))))
```

IndexError: tuple index out of range

**Comment by gillet** [comment]
Hi Hang,
R is crashing for an unknown reason. Can you send me the output of the R c code compilation:
cd ulysses
rm probamaxdist.so probamaxdist.o
R CMD SHLIB probamaxdist.c

Also, can you send me the same output as before after removing probamaxdist.so and probamaxdist.o files.
cd ulysses
rm probamaxdist.so probamaxdist.o
cd example
../Ulysses.py

Alex

**Comment by hangphan** [comment]
Hi Alex,

I recompiled the R code, but there’s nothing abnormal about it 

-bash-4.1$ R CMD SHLIB probamaxdist.c
gcc -std=gnu99 -I/apps/well/R/3.1.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c probamaxdist.c -o probamaxdist.o
gcc -std=gnu99 -shared -L/apps/well/R/3.1.2/lib64/R/lib -L/usr/local/lib64 -o probamaxdist.so probamaxdist.o -L/apps/well/R/3.1.2/lib64/R/lib -lR
-bash-4.1$ 

Best regards,
Hang

**Comment by gillet** [comment]
I cannot manage to reproduce the bug. What OS you are using ? What is your R version ?
You can also re-run the detection in debug mode (you need to replace 2 files in the ulysses directory:
https://dl.dropboxusercontent.com/u/52471317/scriptRClusterSize.R
https://dl.dropboxusercontent.com/u/52471317/Ulysse_stats.py ) and send me the output.
Best, 
Alex

**Comment by hangphan** [comment]
I use a Linux system, not sure which version of Linux, and the R version is
R/3.1.2
Does this ring any bell?

**Comment by gillet** [comment]
I've edited the links in the previous message, one was wrong sorry

**Comment by hangphan** [comment]
Which link was wrong?

**Comment by gillet** [comment]
the first one

**Comment by gillet** [comment]
Your R version looks alright to me (we use the same version). Linux should not be faulty here (some users have had some problems compiling the R code with mac os 10.10).

In you case, R seems to crash only when it writes down some files. There might be something with file permissions. We might have more details with the debug mode.
